version: "3.2"

services:
  glpi:
    image: glpi
    container_name: glpi
    ports:
#      - "80:80"
      - "443:443"
    depends_on:
      - mariadb
    volumes:
      - glpi-data:/data
#      - ./ssl/ssl-cert-glpi.crt:/etc/apache2/ssl/ssl-cert-glpi.crt
#      - ./ssl/ssl-cert-glpi.key:/etc/apache2/ssl/ssl-cert-glpi.key
    restart: always

  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: sadadfrgsfgbsrfg
      MARIADB_DATABASE: glpi
      MARIADB_USER: glpi_user
      MARIADB_PASSWORD: glpi
    restart: always

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  glpi-data:
  mariadb: